CREATE TABLE Bonus(
	"ID" INTEGER NOT NULL,
	"Name" VARCHAR(15) UNIQUE NOT NULL,
	"Description" VARCHAR(20),
	PRIMARY KEY("ID")
);

CREATE TABLE Token(
	"ID" INTEGER NOT NULL,
	"Name" VARCHAR(10) UNIQUE NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE Property(
	"ID" INTEGER NOT NULL,
	"Name" VARCHAR(20) UNIQUE NOT NULL,
	"Cost" INTEGER,
	"Color" VARCHAR(10),
	"OwnerID" INTEGER,
	PRIMARY KEY(ID),
	FOREIGN KEY(OwnerID) REFERENCES Players(ID)
);

CREATE TABLE Players(
	"ID" INTEGER NOT NULL,
	"Player" VARCHAR(10) UNIQUE NOT NULL,
	"Token" VARCHAR(15) UNIQUE NOT NULL,
	"BankBalance" INTEGER,	
	"PropertyID" INTEGER,
	"BonusID" INTEGER,
	PRIMARY KEY(ID),
	FOREIGN KEY(BonusID) REFERENCES Bonus(ID),
	FOREIGN KEY(PropertyID) REFERENCES Property(ID),
	FOREIGN KEY(Token) REFERENCES Token(Name)
);

CREATE TABLE Audit(
	"PlayerID" INTEGER NOT NULL,
	"Updated_Balance" INTEGER,
	"PropertyID" INTEGER,
	"BonusID" INTEGER,
	"GameRound" INTEGER NOT NULL,
	PRIMARY KEY(PlayerID,GameRound),
	FOREIGN KEY(PlayerID) REFERENCES Players(ID)	
);


